trigger:
  - feature/*
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  - ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/main') }}:
    - group: PROD_DEVOPS_TEST_INFRA
  - ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/feature/') }}:
    - group: DEV_DEVOPS_TEST_INFRA
  - name: branch
    value: ${{ variables['Build.SourceBranch'] }}



jobs:
- job: DeployInfraestructure
  displayName: 'Deploy Infraestructure'
  steps:
  - task: TerraformInstaller@0
    displayName: Install Terraform
    inputs:
      terraformVersion: '1.9.6'

  - task: Bash@3
    displayName: Deploy with Terraform
    inputs:
      targetType: 'inline'
      script: |
        echo $(branch)
        terraform init
        terraform plan -var="env_code=$(ENV)" -var="project=$(NAME)" 
        terraform apply -var="env_code=$(ENV)" -var="project=$(NAME)" -auto-approve
    env:
      ARM_CLIENT_ID: $(DEVOPS_TEST_INFRA_CL_ID)
      ARM_CLIENT_SECRET: $(DEVOPS_TEST_INFRA_SEC)
      ARM_TENANT_ID: $(DEVOPS_TEST_INFRA_TENANT)
      ARM_SUBSCRIPTION_ID: $(DEVOPS_TEST_INFRA_SUSC)